#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Any:
def solve(n, a, q, queries):
    ans = []
    for query in queries:
        if query[0] == 1:
            a[query[1] - 1] = query[2]
        elif query[0] == 2:
            ans.append(a[query[1] - 1])
        else:
            raise ValueError()
    return ans

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    n = int(input())
    a = list(map(int, input().split()))
    q = int(input())
    queries = []
    for _ in range(q):
        queries.append(list(map(int, input().split())))
    # print(queries)
    ans = solve(n, a, q, queries)

    print(*ans, sep="\n")  # TODO: edit here


if __name__ == '__main__':
    main()
