#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> Any:
def solve(N):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    ans = solve(N)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
