#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> int:
def solve(N, A):
    odds, even = [], []
    ans = -1
    for x in sorted(A):
        if x % 2 != 0:
            odds.append(x)
        else:
            even.append(x)

    ans = max(odds[-1] + odds[-2], ans) if len(odds) >= 2 else ans
    ans = max(even[-1] + even[-2], ans) if len(even) >= 2 else ans
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A)
    print(a)


if __name__ == '__main__':
    main()
