#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int, C: int, D: int, x: List[int]) -> int:
def solve(N, A, B, C, D, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = int(next(tokens))
    B = int(next(tokens))
    C = int(next(tokens))
    D = int(next(tokens))
    x = [None for _ in range(N)]
    for i in range(N):
        x[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A, B, C, D, x)
    print(a)


if __name__ == '__main__':
    main()
