#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Y: int) -> Tuple[int, int, int]:
def solve(N, Y):
    def price(i, j):
        return i * 10000 + j * 5000 + (N - i - j) * 1000

    ans = (-1, -1, -1)

    for i in range(N+1):
        for j in range((N+1)-i):
            if price(i, j) == Y:
                ans = (i, j, N-i-j)

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Y = map(int, input().split())
    d, e, f = solve(N, Y)
    print(d, e, f)


if __name__ == '__main__':
    main()
