#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, C: int, D: int, E: int) -> int:
def solve(A, B, C, D, E):
    tpl = sorted(((10 - v) % 10, v, (v+10-1)//10*10) for v in [A, B, C, D, E])
    ans = 0

    for i, v in enumerate(tpl):
        if i == (len(tpl)-1):
            ans += v[1]
        else:
            ans += v[2]

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = int(input())
    B = int(input())
    C = int(input())
    D = int(input())
    E = int(input())
    a = solve(A, B, C, D, E)
    print(a)


if __name__ == '__main__':
    main()
