#!/usr/bin/env python3
# from typing import *


# def solve(S: int, K: int) -> int:
def solve(S, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = int(input())
    K = int(input())
    a = solve(S, K)
    print(a)


if __name__ == '__main__':
    main()
