#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, M: int, H: int, K: int, S: str, x: List[int], y: List[int]) -> str:
def solve(N, M, H, K, S, x, y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, H, K = map(int, input().split())
    x = [None for _ in range(M)]
    y = [None for _ in range(M)]
    S = input()
    for i in range(M):
        x[i], y[i] = map(int, input().split())
    a = solve(N, M, H, K, S, x, y)
    print(a)


if __name__ == '__main__':
    main()
