#!/usr/bin/env python3
# from typing import *


# def solve(K: int) -> str:
def solve(K):
    return bin(K)[2:].replace("1", "2")


def solve2(K):
    ans = ""
    shift = 0
    while True:
        if K >> shift & 1:
            ans += "2"
        else:
            if 1 << shift > K:
                break
            else:
                ans += "0"
        shift += 1

    return "".join(reversed(ans))


def solve3(K):
    ans = ""
    k = K

    while k > 0:
        if k % 2 == 0:
            ans += "0"
        else:
            ans += "2"
        k //= 2

    return "".join(reversed(ans))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    # a = solve(K)
    # a = solve2(K)
    a = solve3(K)
    print(a)


if __name__ == '__main__':
    main()
