#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> int:
def solve(s):
    return sum([1 for c in s if c == "1"])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    a = solve(s)
    print(a)


if __name__ == '__main__':
    main()
