#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, X: List[int], C: List[int], Y: List[int]) -> int:
def solve(N, M, X, C, Y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    X = [None for _ in range(N)]
    C = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    for i in range(N):
        X[i] = int(next(tokens))
    for i in range(M):
        C[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, X, C, Y)
    print(a)


if __name__ == '__main__':
    main()
