#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: List[int], T: List[int], U: List[int], V: List[int]) -> List[List[str]]:
def solve(N, S, T, U, V):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    S = [None for _ in range(N)]
    T = [None for _ in range(N)]
    U = [None for _ in range(N)]
    V = [None for _ in range(N)]
    for i in range(N):
        S[i] = int(next(tokens))
    for i in range(N):
        T[i] = int(next(tokens))
    for i in range(N):
        U[i] = int(next(tokens))
    for i in range(N):
        V[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, S, T, U, V)
    for j in range(N):
        print(*[a[j][i] for i in range(N)])


if __name__ == '__main__':
    main()
