#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> int:
def solve(N):
    ans = 0
    dist = 100
    for i in range(0, 100+1, 5):
        # print(i, abs(N-i), dist)
        if abs(N-i) < dist:
            ans = i
            dist = abs(N-i)

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)


if __name__ == '__main__':
    main()
