#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, K: int) -> Tuple[int, int]:
def solve(A, B, K):
    takahashi, aoki = A, B
    for i in range(K):
        if i & 1 == 0:
            takahashi >>= 1
            aoki += takahashi
        else:
            aoki >>= 1
            takahashi += aoki

    return takahashi, aoki


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, K = map(int, input().split())
    c, d = solve(A, B, K)
    print(c, d)


if __name__ == '__main__':
    main()
