#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> int:
def solve(L1, R1, L2, R2):
    return len(list(range(max(L1, L2), min(R1, R2))))


def solve2(L1, R1, L2, R2):
    return len(set(range(L1, R1)) & set(range(L2, R2)))


def solve3(L1, R1, L2, R2):
    ans = 0
    for i in range(100):
        if L1 <= i < R1 and L2 <= i < R2:
            ans += 1
    return ans


def solve4(L1, R1, L2, R2):
    return sum([1 for i in range(100) if L1 <= i < R1 and L2 <= i < R2])


def solve5(L1, R1, L2, R2):
    left, right = max(L1, L2), min(R1, R2)
    return max(right-left, 0)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    L1, R1, L2, R2 = map(int, input().split())
    # a = solve(L1, R1, L2, R2)
    # a = solve2(L1, R1, L2, R2)
    # a = solve3(L1, R1, L2, R2)
    # a = solve4(L1, R1, L2, R2)
    a = solve5(L1, R1, L2, R2)
    print(a)


if __name__ == '__main__':
    main()
