#!/usr/bin/env python3
# from typing import *
from collections import defaultdict, deque


# def solve(N: int, M: int, A: List[int]) -> int:
def solve(N, M, A):
    cards = defaultdict(0)
    for a in A:
        cards[a] += 1

    que = deque(range(M)).rotate(1)
    left = 0

    return None


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, A)
    print(a)


if __name__ == '__main__':
    main()
