#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

auto solve(auto a, const std::vector<auto> &b, const std::vector<auto> &c, const std::vector<auto> &d, auto e, auto f, auto g) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto a, e, f, g;
    std::cin >> a;
    std::vector<auto> b(a), c(a), d(a);
    REP (i, a) { std::cin >> b[i] >> c[i] >> d[i]; }
    std::cin >> e >> f >> g;
    auto ans = solve(a, b, c, d, e, f, g);
    std::cout << a << '\n';
    std::cout << b << '\n';
    std::cout << c << '\n';
    REP (i, c) { std::cout << d[i] << '\n'; }
    return 0;
}
