#!/usr/bin/env python3
# from typing import *
import sys

# def solve(N: int, M: int, C: List[str], D: List[str], P: List[int]) -> int:


def solve(N, M, C, D, P):
    prices = {k: v for k, v in zip(D, P[1:])}
    colors = set(D)
    ans = 0

    # print(prices, colors, file=sys.stderr)

    for c in C:
        # print(c, file=sys.stderr)
        if c not in colors:
            ans += P[0]
        else:
            ans += prices[c]
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    C = [None for _ in range(N)]
    D = [None for _ in range(M)]
    P = [None for _ in range(M + 1)]
    for i in range(N):
        C[i] = next(tokens)
    for i in range(M):
        D[i] = next(tokens)
    for i in range(M + 1):
        P[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, C, D, P)
    print(a)


if __name__ == '__main__':
    main()
