#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, name: str, kit: str) -> int:
def solve(N, M, name, kit):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    name = input()
    kit = input()
    a = solve(N, M, name, kit)
    print(a)


if __name__ == '__main__':
    main()
