#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int) -> Tuple[str, List[str], List[str]]:
def solve(N, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    M, u, v = solve(N, K)
    print(M)
    for i in range(M):
        print(u[i], v[i])


if __name__ == '__main__':
    main()
