#!/usr/bin/env python3
# from typing import *


# def solve(S: int, W: int) -> str:
def solve(S, W):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S, W = map(int, input().split())
    a = solve(S, W)
    print(a)


if __name__ == '__main__':
    main()
