#!/usr/bin/env python3
# from typing import *


# def solve(N: int, L: int) -> int:


def solve(N, L):
    ans = (2 * L + N - 1) * N // 2

    if (L + 1 - 1) <= 0 <= (L + N - 1):
        return ans
    elif (L + N - 1) < 0:
        return ans + abs(L + N - 1)
    else:
        return ans - abs(L + 1 - 1)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    N, L = map(int, input().split())
    a = solve(N, L)
    print(a)


if __name__ == '__main__':
    main()
