#!/usr/bin/env python3
# from typing import *
import itertools
from icecream import ic

# def solve(H: int, M: int) -> Tuple[int, int]:


def hour_24(h, w):
    hour = str(h).zfill(2) if h != 24 else
    minutes = str(w).zfill(2)
    return (int(hour[0]), int(hour[1]), int(minutes[0]), int(minutes[1]))


def solve(H, M):
    times = {hour_24(h, w) for h, w in itertools.product(range(24), range(60))}
    # ic(times)
    for h, m in itertools.product(range(H, 24), range(M, 60)):
        time = hour_24(h, m)
        target = (time[0], time[2], time[1], time[3])
        ic(time, target)
        if target in times:
            return h, m
    for h, m in itertools.product(range(H+1), range(M+1)):
        time = hour_24(h, m)
        target = (time[0], time[2], time[1], time[3])
        ic(time, target)
        if target in times:
            return h, m


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, M = map(int, input().split())
    h, m = solve(H, M)
    print(h, m)


if __name__ == '__main__':
    main()
