#!/usr/bin/env python3
# from typing import *


# def solve(N: int, a: List[int]) -> int:
def solve(N, a):
    alice = bob = 0
    for i, k in enumerate(sorted(a, reverse=True)):
        if i % 2 == 0:
            alice += k
        else:
            bob += k

    return alice - bob
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, a)
    print(a1)


if __name__ == '__main__':
    main()
