#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, x: List[int], y: List[int]) -> Tuple[str, List[str], List[str]]:
def solve(N, K, x, y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i] = map(int, input().split())
    M, p, q = solve(N, K, x, y)
    print(M)
    for i in range(M):
        print(p[i], q[i])


if __name__ == '__main__':
    main()
