#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, Q: int, s: List[int], t: List[int], x: List[int]) -> List[str]:
def solve(A, B, Q, s, t, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, Q = map(int, input().split())
    s = [None for _ in range(A)]
    t = [None for _ in range(B)]
    x = [None for _ in range(Q)]
    for i in range(A):
        s[i] = int(input())
    for i in range(B):
        t[i] = int(input())
    for i in range(Q):
        x[i] = int(input())
    a = solve(A, B, Q, s, t, x)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
