#!/usr/bin/env python3
# from typing import *

import datetime

# def solve(S: str) -> str:


def solve(S):
    HEISEI = datetime.datetime(2019, 4, 30)
    DATE = datetime.datetime.strptime(S, "%Y/%m/%d")

    return "Heisei" if DATE <= HEISEI else "TBD"


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
