#!/usr/bin/env python3
# from typing import *


# def solve(a: int, N: int) -> int:
def solve(a, N):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, N = map(int, input().split())
    a1 = solve(a, N)
    print(a1)


if __name__ == '__main__':
    main()
