#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'


# def solve(S: str) -> str:
def solve(S):
    s = [c for c in S]
    dreamer = "dreamer"
    eraser = "eraser"

    while s:
        if "".join(s[-1 * (len(dreamer)):]) == dreamer:
            for _ in range(len(dreamer)):
                s.pop(-1)
        elif "".join(s[-1 * (len(eraser)):]) == eraser:
            for _ in range(len(eraser)):
                s.pop(-1)
        elif "".join(s[-1 * 5:]) in ["dream", "erase"]:
            for _ in range(5):
                s.pop(-1)
        else:
            return NO

    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
