#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, U: List[int], V: List[int], W: List[int], K: int, A: List[int], D: int, X: List[int]) -> List[str]:
def solve(N, M, U, V, W, K, A, D, X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    W = [None for _ in range(M)]
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
        W[i] = int(next(tokens))
    K = int(next(tokens))
    A = [None for _ in range(K)]
    for i in range(K):
        A[i] = int(next(tokens))
    D = int(next(tokens))
    X = [None for _ in range(D)]
    for i in range(D):
        X[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, M, U, V, W, K, A, D, X)
    for i in range(N):
        print(ans[i])


if __name__ == '__main__':
    main()
