#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, M: int, s: List[int], t: List[int], L: List[int], R: List[int]) -> Tuple[str, List[str]]:
def solve(N, M, s, t, L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    s = [None for _ in range(M)]
    t = [None for _ in range(M)]
    L = [None for _ in range(N)]
    R = [None for _ in range(N)]
    for i in range(M):
        s[i], t[i] = map(int, input().split())
    for i in range(N):
        L[i], R[i] = map(int, input().split())
    Yes, P = solve(N, M, s, t, L, R)
    print(Yes)
    print(*[P[i] for i in range(N)])


if __name__ == '__main__':
    main()
