#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int], Q: int, l: List[int], r: List[int]) -> List[str]:
def solve(N, A, Q, l, r):
    f = dict()

    for i, a in enumerate(A, 1):
        if i % 2 == 0:
            f[i] = f
        else:
            f[i] = 0


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    Q = int(next(tokens))
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    for i in range(Q):
        l[i] = int(next(tokens))
        r[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A, Q, l, r)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
