#!/usr/bin/env python3
# from typing import *


# def solve(N: int, H: int, t: List[int], d: List[int]) -> int:
def solve(N, H, t, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, H = map(int, input().split())
    t = [None for _ in range(N)]
    d = [None for _ in range(N)]
    for i in range(N):
        t[i], d[i] = map(int, input().split())
    a = solve(N, H, t, d)
    print(a)


if __name__ == '__main__':
    main()
