#!/usr/bin/env python3
# from typing import *


# def solve(X: int, Y: int, Z: int, S: str) -> int:
def solve(X, Y, Z, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y, Z = map(int, input().split())
    S = input()
    a = solve(X, Y, Z, S)
    print(a)


if __name__ == '__main__':
    main()
