#!/usr/bin/env python3
# from typing import *


# def solve(N: int, L: int, R: int) -> List[str]:
def solve(N, L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, L, R = map(int, input().split())
    ans = solve(N, L, R)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
