#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, s: List[str]) -> int:
def solve(N, M, s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    s = [None for _ in range(M)]
    for i in range(M):
        s[i] = input()
    a = solve(N, M, s)
    print(a)


if __name__ == '__main__':
    main()
