#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, S: int, U: List[int], V: List[int], A: List[int], B: List[int], C: List[int], D: List[int]) -> List[str]:
def solve(N, M, S, U, V, A, B, C, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, S = map(int, input().split())
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    C = [None for _ in range(N)]
    D = [None for _ in range(N)]
    for i in range(M):
        U[i], V[i], A[i], B[i] = map(int, input().split())
    for i in range(N):
        C[i], D[i] = map(int, input().split())
    a = solve(N, M, S, U, V, A, B, C, D)
    for i in range(N):
        print(a[i])


if __name__ == '__main__':
    main()
