#!/usr/bin/env python3
from typing import Tuple, List

# from icecream import ic


def solve(S: List[str]) -> Tuple[int, int, int, int]:

    def edges(S) -> tuple:
        for i, s in enumerate(S, 1):
            if "#" in s:
                return i, s.find("#") + 1

    a, c, b, d = *edges(S), *edges(reversed(["".join(reversed(s)) for s in S]))
    b, d = -b % 10 + 1, -d % 10 + 1
    return a, b, c, d


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = [None for _ in range(10)]
    for i in range(10):
        S[i] = input()
    A, B, C, D = solve(S)
    print(A, B)
    print(C, D)


if __name__ == '__main__':
    main()
