#!/usr/bin/env python3
# from typing import *


# def solve(S: List[str]) -> Tuple[int, int, int, int]:
def solve(S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = [None for _ in range(10)]
    for i in range(10):
        S[i] = input()
    A, B, C, D = solve(S)
    print(A, B)
    print(C, D)


if __name__ == '__main__':
    main()
