#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, S: int, a: List[int], b: List[int]) -> Any:
def solve(N, S, a, b):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, S = map(int, input().split())
    a = [None for _ in range(N)]
    b = [None for _ in range(N)]
    for i in range(N):
        a[i], b[i] = map(int, input().split())
    ans = solve(N, S, a, b)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
