#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, h: List[int], w: List[int], d: List[int]) -> str:
def solve(N, h, w, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    h = [None for _ in range(N)]
    w = [None for _ in range(N)]
    d = [None for _ in range(N)]
    for i in range(N):
        h[i], w[i], d[i] = map(int, input().split())
    a = solve(N, h, w, d)
    print(a)


if __name__ == '__main__':
    main()
