#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

int64_t solve(int N, int M, const std::vector<int64_t> &X, const std::vector<int64_t> &Y, const std::vector<int64_t> &A, const std::vector<int64_t> &B, const std::vector<int64_t> &Z) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<int64_t> X(N), Y(N);
    std::cin >> M;
    std::vector<int64_t> A(M), B(M), Z(M);
    REP (i, N) { std::cin >> X[i]; }
    REP (i, N) { std::cin >> Y[i]; }
    REP (i, M) { std::cin >> A[i] >> B[i] >> Z[i]; }
    auto ans = solve(N, M, X, Y, A, B, Z);
    std::cout << ans << '\n';
    return 0;
}
