#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, Q: int, L: List[int], R: List[int], p: List[int], q: List[int]) -> List[str]:
def solve(N, M, Q, L, R, p, q):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, Q = map(int, input().split())
    L = [None for _ in range(M)]
    R = [None for _ in range(M)]
    p = [None for _ in range(Q)]
    q = [None for _ in range(Q)]
    for i in range(M):
        L[i], R[i] = map(int, input().split())
    for i in range(Q):
        p[i], q[i] = map(int, input().split())
    a = solve(N, M, Q, L, R, p, q)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
