#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int) -> Tuple[List[str], List[List[str]]]:
def solve(N, M):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    a, c = solve(N, M)
    for i in range(N):
        print(a[i], *[c[i][j] for j in range(M)])


if __name__ == '__main__':
    main()
