#!/usr/bin/env python3
# from typing import *


def solve(N, S):
    max_len = 0
    ans = S
    for left in range(N):
        if S[left] == "(":
            left_bra, right_bra = 1, 0

            for right in range(left+1, N):
                if S[right] == "(":
                    left_bra += 1
                elif S[right] == ")":
                    right_bra += 1

                    if left_bra == right_bra and len(S[left:right+1]) > max_len:
                        # print(S[left:right+1], S[:left], S[right+1:], ans)
                        max_len = len(S[left:right+1])
                        ans = S[:left] + S[right+1:]
    return ans


def solve2(N, S):
    open_bracket = []
    ans = []

    for i, c in enumerate(S):
        if c not in ["(", ")"]:
            ans.append(c)
        elif c == "(":
            ans.append(c)
            open_bracket.append(i)

        else:
            if open_bracket:
                """
                これはWA & TLE
                2 * 10**5くらいの文字列の末尾に()があったらO(N^2)になる
                """
                # ans = ans[:open_bracket.pop()]

                while ans[-1] != "(":
                    ans.pop()
                ans.pop()
                open_bracket.pop()
            else:
                ans.append(c)
        # print(ans, open_bracket)
    return "".join(ans)


def solve3(N, S):
    stack = []
    open_bracket = 0

    for c in S:
        if c == ")" and open_bracket > 0:
            """
            見ている文字が閉じ括弧で、開き括弧を見たことがあるなら
              -> 最後に見た開き括弧まで文字を消す
              -> 開き括弧を消し、カウンタを減算する
            """
            while stack[-1] != "(":
                stack.pop()
            stack.pop()
            open_bracket -= 1
        else:
            """
            「見ている文字が開き括弧 or 英小文字」or「閉じ括弧だったけど開き括弧を見たことがない」
              -> 解答用stackに追加
                -> 開き括弧ならカウンタを上げる
            """
            stack.append(c)
            if c == "(":
                open_bracket += 1

    return "".join(stack)


def solve4(N, S):
    open_bracket = []
    ans = []

    for c in S:
        if c not in ["(", ")"]:
            ans.append(c)
        elif c == "(":
            ans.append(c)
            open_bracket.append(len(ans)-1)
        else:
            if open_bracket:
                """
                これはTLE
                2 * 10**5くらいの文字列の末尾に()があったらO(N^2)になる
                """
                # ans = ans[:open_bracket.pop()]
                for _ in range(len(ans) - open_bracket.pop()):
                    ans.pop()
            else:
                ans.append(c)
        # print(ans, open_bracket)
    return "".join(ans)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    N = int(input())
    S = input()
    ans = solve4(N, S)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
