#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, A: List[int], K: List[int]) -> Tuple[List[str], str]:
def solve(N, Q, A, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    A = [None for _ in range(N)]
    K = [None for _ in range(Q)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(Q):
        K[i] = int(next(tokens))
    assert next(tokens, None) is None
    c, d = solve(N, Q, A, K)
    for i in range(Q):
        print(c[i])
    print(d)


if __name__ == '__main__':
    main()
