#!/usr/bin/env python3
# from typing import *


# def solve(N: int, d: List[int]) -> int:
def solve(N, d):
    return len(set(d))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    d = [None for _ in range(N)]
    for i in range(N):
        d[i] = int(input())
    a = solve(N, d)
    print(a)


if __name__ == '__main__':
    main()
