#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str) -> str:
def solve(N, S):
    return "".join([c*2 for c in S])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
