#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(auto N, const std::vector<std::vector<auto> > &S, const std::vector<std::vector<auto> > &T) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N;
    std::cin >> N;
    std::vector<std::vector<auto> > S(2 * N + 2, std::vector<auto>((N))), T(2 * N + 2, std::vector<auto>((N)));
    REP (j, N + 2) {
        REP (i, N) {
            std::cin >> S[i + j][i];
        }
    }
    REP (j, N + 2) {
        REP (i, N) {
            std::cin >> T[i + j][i];
        }
    }
    auto ans = solve(N, S, T);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
