#!/usr/bin/env python3
# from typing import *

from collections import Counter

# def solve(A: List[int]) -> int:


def solve(A):
    return sum([a * (2**i) for i, a in enumerate(A)])

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = [None for _ in range(64)]
    import sys
    tokens = iter(sys.stdin.read().split())
    for i in range(64):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve2(A)
    print(a)


if __name__ == '__main__':
    main()
