#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, P: List[int], L: List[int], D: List[int]) -> int:
def solve(N, M, P, L, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    P = [None for _ in range(N)]
    L = [None for _ in range(M)]
    D = [None for _ in range(M)]
    for i in range(N):
        P[i] = int(next(tokens))
    for i in range(M):
        L[i] = int(next(tokens))
    for i in range(M):
        D[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, P, L, D)
    print(a)


if __name__ == '__main__':
    main()
