#!/usr/bin/env python3
# from typing import *


# def solve(N: int, H: int, C: List[int], D: List[int]) -> int:
def solve(N, H, C, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, H = map(int, input().split())
    C = [None for _ in range(N)]
    D = [None for _ in range(N)]
    for i in range(N):
        C[i], D[i] = map(int, input().split())
    a = solve(N, H, C, D)
    print(a)


if __name__ == '__main__':
    main()
