#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, M: int, u: List[int], v: List[int], K: int, x: List[int], y: List[int], Q: int, p: List[int], q: List[int]) -> List[str]:
def solve(N, M, u, v, K, x, y, Q, p, q):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = map(int, input().split())
    K = int(input())
    x = [None for _ in range(K)]
    y = [None for _ in range(K)]
    for i in range(K):
        x[i], y[i] = map(int, input().split())
    Q = int(input())
    p = [None for _ in range(Q)]
    q = [None for _ in range(Q)]
    for i in range(Q):
        p[i], q[i] = map(int, input().split())
    a = solve(N, M, u, v, K, x, y, Q, p, q)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
