#!/usr/bin/env python3
# from typing import *


# def solve(t: int) -> int:
def solve(t):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    t = int(input())
    a = solve(t)
    print(a)


if __name__ == '__main__':
    main()
