#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int, C: int, l: List[int]) -> int:
def solve(N, A, B, C, l):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B, C = map(int, input().split())
    l = [None for _ in range(N)]
    for i in range(N):
        l[i] = int(input())
    a = solve(N, A, B, C, l)
    print(a)


if __name__ == '__main__':
    main()
