#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> List[str]:
def solve(N, A):
    # for i in range(N):
    #     print(A[7*i:7*(i+1)])
    return [sum(A[7*i:7*(i+1)]) for i in range(N)]

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)


def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(7 * N)]
    for i in range(7 * N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, A)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
