#!/usr/bin/env python3
# from typing import *


# def solve(L: int, W: int, S: str, P: str) -> int:
def solve(L, W, S, P):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    L, W = map(int, input().split())
    S = input()
    P = input()
    a = solve(L, W, S, P)
    print(a)


if __name__ == '__main__':
    main()
