#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(S: str, T: str) -> str:
def solve(S, T):
    return YES if len(S) <= len(T) and S == T[:len(S)] else NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    T = input()
    a = solve(S, T)
    print(a)


if __name__ == '__main__':
    main()
