#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, c: int, d: int) -> Tuple[int, str]:
def solve(a, b, c, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c, d = map(int, input().split())
    g, h = solve(a, b, c, d)
    print(g)
    print(h)


if __name__ == '__main__':
    main()
