#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


def check_suit(s: str) -> bool:
    return s[0] in {
        "H",
        "D",
        "C",
        "S",
    }


def check_number(s: str) -> bool:
    return s[1] in {
        "A",
        "T",
        "J",
        "Q",
        "K",
        *[str(i) for i in range(2, 10)],
    }


def check_duplication(lst: list) -> bool:
    return len(lst) == len(set(lst))


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    for s in S:
        if not (check_suit(s) and check_number(s)):
            return NO
    else:
        return YES if check_duplication(S) else NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
